default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_finder_development
  username: <%= Rails.application.credentials.development&.dig(:postgres_user) %>
  password: <%= Rails.application.credentials.development&.dig(:postgres_password) %>

test:
  <<: *default
  database: recipe_finder_test
  username: recipe_finder
  password:

production:
  <<: *default
  database: recipe_finder_production
  url: <%= ENV.fetch("DATABASE_URL") { 'postgres://gmyztntwobtote:e6b3e5949b293e85207b490e683143b1e5701054c518e9646bd3cdc6c69b6ebf@ec2-107-21-67-46.compute-1.amazonaws.com:5432/d4ooep2tq4sjoo' } %>
