default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_finder_development
  username: <%= Rails.application.credentials.development&.dig(:postgres_user) %>
  password: <%= Rails.application.credentials.development&.dig(:postgres_password) %>

test:
  <<: *default
  database: recipe_finder_test
  username: recipe_finder
  password:

production:
  <<: *default
  database: recipe_finder_production
  username: <%= Rails.application.credentials.production&.dig(:postgres_user) %>
  password: <%= Rails.application.credentials.production&.dig(:postgres_password) %>